name: spark-digitaltwin-reader-ci

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        sparkVersion: [ 3.0.3, 3.1.2, 3.1.3, 3.2.1 ]
    
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout with LFS
        uses: actions/checkout@v3.0.1
        with:
          lfs: true
      
      - name: Setup Java JDK
        uses: actions/setup-java@v3.1.1
        with:
          java-version: '8'
          # Java distribution. See the list of supported distributions in README file
          distribution: 'adopt'
      
      - name: Run tests and produce code coverage
        run: sbt -DsparkVersion="${{matrix.sparkVersion}}" clean coverageOn test coverageReport
      
      # Once made public then upload coverage information to codecov
      
      - name: Create assembly
        if: ${{ github.event_name != 'pull_request' }}
        run: sbt -DsparkVersion="${{matrix.sparkVersion}}" clean coverageOff assembly

      - name: Upload assembly
        if: ${{ github.event_name != 'pull_request' }}
        uses: actions/upload-artifact@v3.0.0
        with:
          path: ./target/spark-${{ matrix.sparkVersion }}/scala-2.12/spark-azure-digital-twin*.jar
          if-no-files-found: warn
